/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fah
 */
public class raporlar extends javax.swing.JFrame {

    /**
     * Creates new form raporlar
     */
    public raporlar() {
        initComponents();
        
        String baslik[] = new String[]{"Kategori", "Ürün Adı","Fiyat", "Adet", "Toplam Ücret" };  

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = null;
            Statement st,st1 = null;
            ResultSet rs,rs1 = null;
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/stok?useUnicode=true&characterEncoding=UTF-8", "root", "");
            
            st = con.createStatement();
            st1 = con.createStatement();
            
            rs = st.executeQuery("select *, (fiyat*adet) as Toplam_Fiyat from satislar");
            rs.last();
            
            int ali = Integer.parseInt(rs.getString("Toplam_Fiyat"));
            
           // alttaki 3 satırda raporlar formundak toplam tutarı ekrana yazdırdık
            rs1 = st1.executeQuery("select sum(fiyat*adet) as ToplamFiyat from satislar");
            rs1.last();
            txt_toplam_tutar.setText(rs1.getString(1)+" TL");
            
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("kategori"),  
                    rs.getString("urunadi"), 
                    rs.getString("fiyat"),
                    rs.getString("adet"),
                    rs.getString("Toplam_Fiyat")
                };
                i++;
            }
            
            
            con.close();
            table_rapor.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_satis = new javax.swing.JLabel();
        txt_toplam_tutar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_rapor = new javax.swing.JTable();
        btn_cikis2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        lbl_satis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_satis.setForeground(new java.awt.Color(255, 255, 255));
        lbl_satis.setText("TOTAL SALES AMOUNT");
        getContentPane().add(lbl_satis);
        lbl_satis.setBounds(10, 11, 210, 22);

        txt_toplam_tutar.setEnabled(false);
        getContentPane().add(txt_toplam_tutar);
        txt_toplam_tutar.setBounds(230, 10, 170, 30);

        table_rapor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_rapor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 740, 284);

        btn_cikis2.setText("LOGOUT");
        btn_cikis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikis2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis2);
        btn_cikis2.setBounds(693, 10, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/bg.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cikis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikis2ActionPerformed

        raporlar kapat = new raporlar();
        kapat.setVisible(false);
        dispose();

    }//GEN-LAST:event_btn_cikis2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new raporlar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_satis;
    private javax.swing.JTable table_rapor;
    private javax.swing.JTextField txt_toplam_tutar;
    // End of variables declaration//GEN-END:variables
}
