/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author fah
 */
public class unuttum extends javax.swing.JFrame {

    /**
     * Creates new form unuttum
     */
    public unuttum() {
        initComponents();
        txt_kadi.setBackground(new Color(0, 0, 0, 0));
        txt_kadi.setBorder(null);
        
        txt_email.setBackground(new Color(0, 0, 0, 0));
        txt_email.setBorder(null);
        btn_sifre_goster.setBackground(new Color(0, 0, 0, 0));
        btn_sifre_goster.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        btn_sifre_goster = new javax.swing.JButton();
        txt_kadi = new javax.swing.JTextField();
        btn_cikis = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        lbl_email1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/parolami-unuttum.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(701, 530));
        jLabel1.setMinimumSize(new java.awt.Dimension(701, 530));
        jLabel1.setPreferredSize(new java.awt.Dimension(701, 530));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(701, 530));
        setMinimumSize(new java.awt.Dimension(701, 530));
        setPreferredSize(new java.awt.Dimension(701, 530));
        getContentPane().setLayout(null);

        lbl_email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 102, 255));
        lbl_email.setText("USERNAME");
        getContentPane().add(lbl_email);
        lbl_email.setBounds(0, 220, 150, 22);

        btn_sifre_goster.setText("SHOW PASSWORD");
        btn_sifre_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sifre_gosterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sifre_goster);
        btn_sifre_goster.setBounds(450, 220, 150, 80);

        txt_kadi.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        txt_kadi.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(txt_kadi);
        txt_kadi.setBounds(210, 220, 210, 30);

        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis);
        btn_cikis.setBounds(470, 140, 63, 25);

        txt_email.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(txt_email);
        txt_email.setBounds(210, 270, 210, 30);

        lbl_email1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_email1.setForeground(new java.awt.Color(0, 102, 255));
        lbl_email1.setText("EMAİL");
        getContentPane().add(lbl_email1);
        lbl_email1.setBounds(0, 270, 170, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stok_takip/elegant-black-handmade-technique-aquarelle_23-2148300751.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sifre_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sifre_gosterActionPerformed

        String kadi=txt_kadi.getText();
        String email=txt_email.getText();

        try {

            if (email.equals("")) {

                JOptionPane.showMessageDialog(this, "Lütfen E-Posta Adresinizi Giriniz!");

            } else {
                Class.forName("com.mysql.jdbc.Driver");

                Connection con = null;
                Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/stok?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();

                rs = st.executeQuery("select * from uyeler where kadi='"+kadi+"' and email='"+email+"'");

                if(rs.next()){

                    JOptionPane.showMessageDialog(null, "Şifreniz: " + rs.getString("sifre"));
                    
                    uye_giris ac = new uye_giris();
                    ac.setVisible(true);

                    this.setVisible(false);

                }
                else{
                    JOptionPane.showMessageDialog(null, "Böyle Bir E-Posta Kayıtlı Değil!");
                }
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

    }//GEN-LAST:event_btn_sifre_gosterActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed

        unuttum a = new unuttum();
        a.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unuttum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_sifre_goster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_email1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_kadi;
    // End of variables declaration//GEN-END:variables
}
