/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fah
 */
public class uye_giris extends javax.swing.JFrame {

    /**
     * Creates new form uye_giris
     */
    public uye_giris() {
        initComponents();
        
        txt_kadi.setBackground(new Color(0, 0, 0, 0));
        txt_kadi.setBorder(null);
        
        txt_sifre.setBackground(new Color(0, 0, 0, 0));
        txt_sifre.setBorder(null);
        btn_giris.setBackground(new Color(0, 0, 0, 0));
        btn_giris.setBorder(null);
        lbl_sifremi_unuttum.setBackground(new Color(0, 0, 0, 0));
        lbl_sifremi_unuttum.setBorder(null);
        lbl_uye_ol.setBackground(new Color(0, 0, 0, 0));
        lbl_uye_ol.setBorder(null);
        btn_cikis.setBackground(new Color(0, 0, 0, 0));
        btn_cikis.setBorder(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resim = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_kadi = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JPasswordField();
        btn_giris = new javax.swing.JButton();
        lbl_sifremi_unuttum = new javax.swing.JLabel();
        btn_cikis = new javax.swing.JButton();
        lbl_uye_ol = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        resim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/giris.png"))); // NOI18N
        resim.setText("jLabel2");
        resim.setMaximumSize(new java.awt.Dimension(640, 480));
        resim.setMinimumSize(new java.awt.Dimension(640, 480));
        resim.setName(""); // NOI18N
        resim.setPreferredSize(new java.awt.Dimension(640, 480));

        jLabel3.setText("jLabel3");

        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stok_takip/elegant-black-handmade-technique-aquarelle_23-2148300751.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        txt_kadi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_kadi.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(txt_kadi);
        txt_kadi.setBounds(210, 200, 220, 30);

        txt_sifre.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(txt_sifre);
        txt_sifre.setBounds(210, 260, 220, 30);

        btn_giris.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_giris.setForeground(new java.awt.Color(0, 51, 153));
        btn_giris.setText("LOGIN");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_giris);
        btn_giris.setBounds(450, 200, 110, 90);

        lbl_sifremi_unuttum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_sifremi_unuttum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_sifremi_unuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sifremi_unuttumMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_sifremi_unuttum);
        lbl_sifremi_unuttum.setBounds(400, 340, 140, 14);

        btn_cikis.setForeground(new java.awt.Color(0, 51, 153));
        btn_cikis.setText("LOGOUT");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis);
        btn_cikis.setBounds(450, 110, 90, 40);

        lbl_uye_ol.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_uye_ol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_uye_olMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_uye_ol);
        lbl_uye_ol.setBounds(410, 350, 76, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 210, 80, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 260, 70, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stok_takip/elegant-black-handmade-technique-aquarelle_23-2148300751.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 610, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed

         try {
            
            String kadi=txt_kadi.getText();
            String sifre=txt_sifre.getText();

            if (kadi.equals("") || sifre.equals("")) {

                JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

            } else {
                
                Connection con = null;
                java.sql.Statement st = null;
                ResultSet rs = null;
                
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/stok?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();
                
                rs = st.executeQuery("select * from uyeler where kadi='"+kadi+"' and sifre='"+sifre+"'");
                
                if(rs.last()){
                        
                        if(rs.getString("kategori").equals("Müdür")){
                            ana_ekran ac = new ana_ekran();
                            ac.setVisible(true);
                        }
                        else if(rs.getString("kategori").equals("Satış Danışmanı")){
                            urun_ekle ac = new urun_ekle();
                            ac.setVisible(true);
                        }
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Kullanıcı Adı veya Parola Hatalı! "); 
                    }
                
            }
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

    }//GEN-LAST:event_btn_girisActionPerformed

    private void lbl_sifremi_unuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sifremi_unuttumMouseClicked

        unuttum goster = new unuttum();
        goster.setVisible(true);

    }//GEN-LAST:event_lbl_sifremi_unuttumMouseClicked

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed

        raporlar kapat = new raporlar();
        kapat.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void lbl_uye_olMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_uye_olMouseClicked
        
        uye_ekle ac = new uye_ekle();
        ac.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_lbl_uye_olMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uye_giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_sifremi_unuttum;
    private javax.swing.JLabel lbl_uye_ol;
    private javax.swing.JLabel resim;
    private javax.swing.JTextField txt_kadi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
